### ISSUE TITLE
Source and build?

### ISSUE THREAD

**Issue by yhyu13** [Crispher/MathlibExplorer#2]
HI,

Would you release the build project and soruce so that we can compile for platform like linux adm64?

Thanks!

**Comment by Crispher** [comment]
I don't think the code can be built as is on Linux. It has platform specific implementation that needs porting. I myself spent days to build it on Windows.

I wrote it inside an indie game project. It would require quite some work to separate the visualizer from the rest and make it readable. That being said, if more people are interested and committed to making some contribution, I will certainly consider it.
