### ISSUE TITLE
对这个可视化的方法感到好奇

### ISSUE THREAD

**Issue by auravan** [Crispher/MathlibExplorer#8]
说起来有些不太相关，但是这个支持缩放渐进可视化的方法让我想到了一个之前特别感兴趣的网站。https://musicmap.info/
可不可以稍微给一些这方面的clue和project推荐？

**Comment by Crispher** [comment]
这个只是模仿了一般地图软件缩放展示地名的做法，只需要设定文字与缩放之间的对应关系就行。
另外你提到的网站看上去很有趣！
